final class RuleData {
    public static final Map rules =
            // rulesets/basic.xml
            [AssertWithinFinallyBlock                          : [categories: ['Bug Risk'], points : 50000 ],
             AssignmentInConditional                           : [categories: ['Bug Risk'], points : 50000 ],
             BigDecimalInstantiation                           : [categories: ['Bug Risk'], points : 50000 ],
             BitwiseOperatorInConditional                      : [categories: ['Bug Risk'], points : 50000 ],
             BooleanGetBoolean                                 : [categories: ['Bug Risk'], points : 50000 ],
             BrokenNullCheck                                   : [categories: ['Bug Risk'], points : 50000 ],
             BrokenOddnessCheck                                : [categories: ['Bug Risk'], points : 50000 ],
             ClassForName                                      : [categories: ['Bug Risk'], points : 50000 ],
             ComparisonOfTwoConstants                          : [categories: ['Bug Risk'], points : 50000 ],
             ComparisonWithSelf                                : [categories: ['Bug Risk'], points : 50000 ],
             ConstantAssertExpression                          : [categories: ['Bug Risk'], points : 50000 ],
             ConstantIfExpression                              : [categories: ['Bug Risk'], points : 50000 ],
             ConstantTernaryExpression                         : [categories: ['Bug Risk'], points : 50000 ],
             DeadCode                                          : [categories: ['Bug Risk'], points : 50000 ],
             DoubleNegative                                    : [categories: ['Bug Risk'], points : 50000 ],
             DuplicateCaseStatement                            : [categories: ['Bug Risk'], points : 50000 ],
             DuplicateMapKey                                   : [categories: ['Bug Risk'], points : 50000 ],
             DuplicateSetValue                                 : [categories: ['Bug Risk'], points : 50000 ],
             EmptyCatchBlock                                   : [categories: ['Bug Risk'], points : 50000 ],
             EmptyClass                                        : [categories: ['Bug Risk'], points : 50000 ],
             EmptyElseBlock                                    : [categories: ['Bug Risk'], points : 50000 ],
             EmptyFinallyBlock                                 : [categories: ['Bug Risk'], points : 50000 ],
             EmptyForStatement                                 : [categories: ['Bug Risk'], points : 50000 ],
             EmptyIfStatement                                  : [categories: ['Bug Risk'], points : 50000 ],
             EmptyInstanceInitializer                          : [categories: ['Bug Risk'], points : 50000 ],
             EmptyMethod                                       : [categories: ['Bug Risk'], points : 50000 ],
             EmptyStaticInitializer                            : [categories: ['Bug Risk'], points : 50000 ],
             EmptySwitchStatement                              : [categories: ['Bug Risk'], points : 50000 ],
             EmptySynchronizedStatement                        : [categories: ['Bug Risk'], points : 50000 ],
             EmptyTryBlock                                     : [categories: ['Bug Risk'], points : 50000 ],
             EmptyWhileStatement                               : [categories: ['Bug Risk'], points : 50000 ],
             EqualsAndHashCode                                 : [categories: ['Bug Risk'], points : 50000 ],
             EqualsOverloaded                                  : [categories: ['Bug Risk'], points : 50000 ],
             ExplicitGarbageCollection                         : [categories: ['Bug Risk'], points : 50000 ],
             ForLoopShouldBeWhileLoop                          : [categories: ['Bug Risk'], points : 50000 ],
             HardCodedWindowsFileSeparator                     : [categories: ['Bug Risk'], points : 50000 ],
             HardCodedWindowsRootDirectory                     : [categories: ['Bug Risk'], points : 50000 ],
             IntegerGetInteger                                 : [categories: ['Bug Risk'], points : 50000 ],
             MultipleUnaryOperators                            : [categories: ['Bug Risk'], points : 50000 ],
             RandomDoubleCoercedToZero                         : [categories: ['Bug Risk'], points : 50000 ],
             RemoveAllOnSelf                                   : [categories: ['Bug Risk'], points : 50000 ],
             ReturnFromFinallyBlock                            : [categories: ['Bug Risk'], points : 50000 ],
             ThrowExceptionFromFinallyBlock                    : [categories: ['Bug Risk'], points : 50000 ],

             // rulesets/braces.xml
             ElseBlockBraces                                   : [categories: ['Style'], points : 50000 ],
             ForStatementBraces                                : [categories: ['Style'], points : 50000 ],
             IfStatementBraces                                 : [categories: ['Style'], points : 50000 ],
             WhileStatementBraces                              : [categories: ['Style'], points : 50000 ],

             // rulesets/concurrency.xml
             BusyWait                                          : [categories: ['Bug Risk'], points : 50000 ],
             DoubleCheckedLocking                              : [categories: ['Bug Risk'], points : 50000 ],
             InconsistentPropertyLocking                       : [categories: ['Bug Risk'], points : 50000 ],
             InconsistentPropertySynchronization               : [categories: ['Bug Risk'], points : 50000 ],
             NestedSynchronization                             : [categories: ['Bug Risk'], points : 50000 ],
             StaticCalendarField                               : [categories: ['Bug Risk'], points : 50000 ],
             StaticConnection                                  : [categories: ['Bug Risk'], points : 50000 ],
             StaticDateFormatField                             : [categories: ['Bug Risk'], points : 50000 ],
             StaticMatcherField                                : [categories: ['Bug Risk'], points : 50000 ],
             StaticSimpleDateFormatField                       : [categories: ['Bug Risk'], points : 50000 ],
             SynchronizedMethod                                : [categories: ['Bug Risk'], points : 50000 ],
             SynchronizedOnBoxedPrimitive                      : [categories: ['Bug Risk'], points : 50000 ],
             SynchronizedOnGetClass                            : [categories: ['Bug Risk'], points : 50000 ],
             SynchronizedOnReentrantLock                       : [categories: ['Bug Risk'], points : 50000 ],
             SynchronizedOnString                              : [categories: ['Bug Risk'], points : 50000 ],
             SynchronizedOnThis                                : [categories: ['Bug Risk'], points : 50000 ],
             SynchronizedReadObjectMethod                      : [categories: ['Bug Risk'], points : 50000 ],
             SystemRunFinalizersOnExit                         : [categories: ['Bug Risk'], points : 50000 ],
             ThisReferenceEscapesConstructor                   : [categories: ['Bug Risk'], points : 50000 ],
             ThreadGroup                                       : [categories: ['Bug Risk'], points : 50000 ],
             ThreadLocalNotStaticFinal                         : [categories: ['Bug Risk'], points : 50000 ],
             ThreadYield                                       : [categories: ['Bug Risk'], points : 50000 ],
             UseOfNotifyMethod                                 : [categories: ['Bug Risk'], points : 50000 ],
             VolatileArrayField                                : [categories: ['Bug Risk'], points : 50000 ],
             VolatileLongOrDoubleField                         : [categories: ['Bug Risk'], points : 50000 ],
             WaitOutsideOfWhileLoop                            : [categories: ['Bug Risk'], points : 50000 ],

             // rulesets/convention.xml
             ConfusingTernary                                  : [categories: ['Style', 'Clarity'], points : 50000 ],
             CouldBeElvis                                      : [categories: ['Style', 'Clarity'], points : 50000 ],
             CouldBeSwitchStatement                            : [categories: ['Style', 'Clarity'], points : 50000 ],
             HashtableIsObsolete                               : [categories: ['Style'], points : 50000 ],
             IfStatementCouldBeTernary                         : [categories: ['Style', 'Clarity'], points : 50000 ],
             InvertedIfElse                                    : [categories: ['Style', 'Clarity'], points : 50000 ],
             LongLiteralWithLowerCaseL                         : [categories: ['Style'], points : 50000 ],
             NoDef                                             : [categories: ['Style'], points : 50000 ],
             NoTabCharacter                                    : [categories: ['Style'], points : 50000 ],
             ParameterReassignment                             : [categories: ['Style', 'Clarity'], points : 50000 ],
             TernaryCouldBeElvis                               : [categories: ['Style', 'Clarity'], points : 50000 ],
             TrailingComma                                     : [categories: ['Style'], points : 50000 ],
             VectorIsObsolete                                  : [categories: ['Style'], points : 50000 ],

             // rulesets/design.xml
             AbstractClassWithPublicConstructor                : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             AbstractClassWithoutAbstractMethod                : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             AssignmentToStaticFieldFromInstanceMethod         : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             BooleanMethodReturnsNull                          : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             BuilderMethodWithSideEffects                      : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             CloneableWithoutClone                             : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             CloseWithoutCloseable                             : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             CompareToWithoutComparable                        : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             ConstantsOnlyInterface                            : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             EmptyMethodInAbstractClass                        : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             FinalClassWithProtectedMember                     : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             ImplementationAsType                              : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             Instanceof                                        : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             LocaleSetDefault                                  : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             NestedForLoop                                     : [categories: ['Style', 'Complexity'], points : 50000 ],
             PrivateFieldCouldBeFinal                          : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             PublicInstanceField                               : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             ReturnsNullInsteadOfEmptyArray                    : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             ReturnsNullInsteadOfEmptyCollection               : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             SimpleDateFormatMissingLocale                     : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             StatelessSingleton                                : [categories: ['Style', 'Complexity'], points : 50000 ],
             ToStringReturnsNull                               : [categories: ['Style', 'Bug Risk'], points : 50000 ],

             // rulesets/dry.xml
             DuplicateListLiteral                              : [categories: ['Duplication'], points : 50000 ],
             DuplicateMapLiteral                               : [categories: ['Duplication'], points : 50000 ],
             DuplicateNumberLiteral                            : [categories: ['Duplication'], points : 50000 ],
             DuplicateStringLiteral                            : [categories: ['Duplication'], points : 50000 ],

             // rulesets/enhanced.xml
             CloneWithoutCloneable                             : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitAssertEqualsConstantActualValue              : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             MissingOverrideAnnotation                         : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             UnsafeImplementationAsMap                         : [categories: ['Style', 'Bug Risk'], points : 50000 ],

             // rulesets/exceptions.xml
             CatchArrayIndexOutOfBoundsException               : [categories: ['Style'], points : 50000 ],
             CatchError                                        : [categories: ['Style'], points : 50000 ],
             CatchException                                    : [categories: ['Style'], points : 50000 ],
             CatchIllegalMonitorStateException                 : [categories: ['Style'], points : 50000 ],
             CatchIndexOutOfBoundsException                    : [categories: ['Style'], points : 50000 ],
             CatchNullPointerException                         : [categories: ['Style'], points : 50000 ],
             CatchRuntimeException                             : [categories: ['Style'], points : 50000 ],
             CatchThrowable                                    : [categories: ['Style'], points : 50000 ],
             ConfusingClassNamedException                      : [categories: ['Style'], points : 50000 ],
             ExceptionExtendsError                             : [categories: ['Style'], points : 50000 ],
             ExceptionExtendsThrowable                         : [categories: ['Style'], points : 50000 ],
             ExceptionNotThrown                                : [categories: ['Style'], points : 50000 ],
             MissingNewInThrowStatement                        : [categories: ['Style'], points : 50000 ],
             ReturnNullFromCatchBlock                          : [categories: ['Style'], points : 50000 ],
             SwallowThreadDeath                                : [categories: ['Style'], points : 50000 ],
             ThrowError                                        : [categories: ['Style'], points : 50000 ],
             ThrowException                                    : [categories: ['Style'], points : 50000 ],
             ThrowNullPointerException                         : [categories: ['Style'], points : 50000 ],
             ThrowRuntimeException                             : [categories: ['Style'], points : 50000 ],
             ThrowThrowable                                    : [categories: ['Style'], points : 50000 ],

             // rulesets/formatting.xml
             BlankLineBeforePackage                            : [categories: ['Style'], points : 50000 ],
             BracesForClass                                    : [categories: ['Style'], points : 50000 ],
             BracesForForLoop                                  : [categories: ['Style'], points : 50000 ],
             BracesForIfElse                                   : [categories: ['Style'], points : 50000 ],
             BracesForMethod                                   : [categories: ['Style'], points : 50000 ],
             BracesForTryCatchFinally                          : [categories: ['Style'], points : 50000 ],
             ClassJavadoc                                      : [categories: ['Style'], points : 50000 ],
             ClosureStatementOnOpeningLineOfMultipleLineClosure: [categories: ['Style'], points : 50000 ],
             ConsecutiveBlankLines                             : [categories: ['Style'], points : 50000 ],
             FileEndsWithoutNewline                            : [categories: ['Style'], points : 50000 ],
             LineLength                                        : [categories: ['Style'], points : 50000 ],
             MissingBlankLineAfterImports                      : [categories: ['Style'], points : 50000 ],
             MissingBlankLineAfterPackage                      : [categories: ['Style'], points : 50000 ],
             SpaceAfterCatch                                   : [categories: ['Style'], points : 50000 ],
             SpaceAfterClosingBrace                            : [categories: ['Style'], points : 50000 ],
             SpaceAfterComma                                   : [categories: ['Style'], points : 50000 ],
             SpaceAfterFor                                     : [categories: ['Style'], points : 50000 ],
             SpaceAfterIf                                      : [categories: ['Style'], points : 50000 ],
             SpaceAfterOpeningBrace                            : [categories: ['Style'], points : 50000 ],
             SpaceAfterSemicolon                               : [categories: ['Style'], points : 50000 ],
             SpaceAfterSwitch                                  : [categories: ['Style'], points : 50000 ],
             SpaceAfterWhile                                   : [categories: ['Style'], points : 50000 ],
             SpaceAroundClosureArrow                           : [categories: ['Style'], points : 50000 ],
             SpaceAroundMapEntryColon                          : [categories: ['Style'], points : 50000 ],
             SpaceAroundOperator                               : [categories: ['Style'], points : 50000 ],
             SpaceBeforeClosingBrace                           : [categories: ['Style'], points : 50000 ],
             SpaceBeforeOpeningBrace                           : [categories: ['Style'], points : 50000 ],
             TrailingWhitespace                                : [categories: ['Style'], points : 50000 ],

             // rulesets/generic.xml
             IllegalClassMember                                : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             IllegalClassReference                             : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             IllegalPackageReference                           : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             IllegalRegex                                      : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             IllegalString                                     : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             IllegalSubclass                                   : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             RequiredRegex                                     : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             RequiredString                                    : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             StatelessClass                                    : [categories: ['Style', 'Bug Risk'], points : 50000 ],

             // rulesets/grails.xml
             GrailsDomainHasEquals                             : [categories: ['Style'], points : 50000 ],
             GrailsDomainHasToString                           : [categories: ['Style'], points : 50000 ],
             GrailsDomainReservedSqlKeywordName                : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             GrailsDomainWithServiceReference                  : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             GrailsDuplicateConstraint                         : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             GrailsDuplicateMapping                            : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             GrailsMassAssignment                              : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             GrailsPublicControllerMethod                      : [categories: ['Style', 'Security'], points : 50000 ],
             GrailsServletContextReference                     : [categories: ['Style'], points : 50000 ],
             GrailsStatelessService                            : [categories: ['Style'], points : 50000 ],

             // rulesets/groovyism.xml
             AssignCollectionSort                              : [categories: ['Style'], points : 50000 ],
             AssignCollectionUnique                            : [categories: ['Style'], points : 50000 ],
             ClosureAsLastMethodParameter                      : [categories: ['Style'], points : 50000 ],
             CollectAllIsDeprecated                            : [categories: ['Style'], points : 50000 ],
             ConfusingMultipleReturns                          : [categories: ['Style', 'Clarity'], points : 50000 ],
             ExplicitArrayListInstantiation                    : [categories: ['Style'], points : 50000 ],
             ExplicitCallToAndMethod                           : [categories: ['Style'], points : 50000 ],
             ExplicitCallToCompareToMethod                     : [categories: ['Style'], points : 50000 ],
             ExplicitCallToDivMethod                           : [categories: ['Style'], points : 50000 ],
             ExplicitCallToEqualsMethod                        : [categories: ['Style'], points : 50000 ],
             ExplicitCallToGetAtMethod                         : [categories: ['Style'], points : 50000 ],
             ExplicitCallToLeftShiftMethod                     : [categories: ['Style'], points : 50000 ],
             ExplicitCallToMinusMethod                         : [categories: ['Style'], points : 50000 ],
             ExplicitCallToModMethod                           : [categories: ['Style'], points : 50000 ],
             ExplicitCallToMultiplyMethod                      : [categories: ['Style'], points : 50000 ],
             ExplicitCallToOrMethod                            : [categories: ['Style'], points : 50000 ],
             ExplicitCallToPlusMethod                          : [categories: ['Style'], points : 50000 ],
             ExplicitCallToPowerMethod                         : [categories: ['Style'], points : 50000 ],
             ExplicitCallToRightShiftMethod                    : [categories: ['Style'], points : 50000 ],
             ExplicitCallToXorMethod                           : [categories: ['Style'], points : 50000 ],
             ExplicitHashMapInstantiation                      : [categories: ['Style'], points : 50000 ],
             ExplicitHashSetInstantiation                      : [categories: ['Style'], points : 50000 ],
             ExplicitLinkedHashMapInstantiation                : [categories: ['Style'], points : 50000 ],
             ExplicitLinkedListInstantiation                   : [categories: ['Style'], points : 50000 ],
             ExplicitStackInstantiation                        : [categories: ['Style'], points : 50000 ],
             ExplicitTreeSetInstantiation                      : [categories: ['Style'], points : 50000 ],
             GStringAsMapKey                                   : [categories: ['Style'], points : 50000 ],
             GStringExpressionWithinString                     : [categories: ['Style'], points : 50000 ],
             GetterMethodCouldBeProperty                       : [categories: ['Style'], points : 50000 ],
             GroovyLangImmutable                               : [categories: ['Style'], points : 50000 ],
             UseCollectMany                                    : [categories: ['Style'], points : 50000 ],
             UseCollectNested                                  : [categories: ['Style'], points : 50000 ],

             // rulesets/imports.xml
             DuplicateImport                                   : [categories: ['Style'], points : 50000 ],
             ImportFromSamePackage                             : [categories: ['Style'], points : 50000 ],
             ImportFromSunPackages                             : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             MisorderedStaticImports                           : [categories: ['Style'], points : 50000 ],
             NoWildcardImports                                 : [categories: ['Style'], points : 50000 ],
             UnnecessaryGroovyImport                           : [categories: ['Style'], points : 50000 ],
             UnusedImport                                      : [categories: ['Style'], points : 50000 ],

             // rulesets/jdbc.xml
             DirectConnectionManagement                        : [categories: ['Style'], points : 50000 ],
             JdbcConnectionReference                           : [categories: ['Style'], points : 50000 ],
             JdbcResultSetReference                            : [categories: ['Style'], points : 50000 ],
             JdbcStatementReference                            : [categories: ['Style'], points : 50000 ],

             // rulesets/junit.xml
             ChainedTest                                       : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             CoupledTestCase                                   : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitAssertAlwaysFails                            : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitAssertAlwaysSucceeds                         : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitFailWithoutMessage                           : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitLostTest                                     : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitPublicField                                  : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitPublicNonTestMethod                          : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitPublicProperty                               : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitSetUpCallsSuper                              : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitStyleAssertions                              : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitTearDownCallsSuper                           : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitTestMethodWithoutAssert                      : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitUnnecessarySetUp                             : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitUnnecessaryTearDown                          : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             JUnitUnnecessaryThrowsException                   : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             SpockIgnoreRestUsed                               : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             UnnecessaryFail                                   : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             UseAssertEqualsInsteadOfAssertTrue                : [categories: ['Style'], points : 50000 ],
             UseAssertFalseInsteadOfNegation                   : [categories: ['Style'], points : 50000 ],
             UseAssertNullInsteadOfAssertEquals                : [categories: ['Style'], points : 50000 ],
             UseAssertSameInsteadOfAssertTrue                  : [categories: ['Style'], points : 50000 ],
             UseAssertTrueInsteadOfAssertEquals                : [categories: ['Style'], points : 50000 ],
             UseAssertTrueInsteadOfNegation                    : [categories: ['Style'], points : 50000 ],

             // rulesets/logging.xml
             LoggerForDifferentClass                           : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             LoggerWithWrongModifiers                          : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             LoggingSwallowsStacktrace                         : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             MultipleLoggers                                   : [categories: ['Style', 'Bug Risk'], points : 50000 ],
             PrintStackTrace                                   : [categories: ['Style'], points : 50000 ],
             Println                                           : [categories: ['Style'], points : 50000 ],
             SystemErrPrint                                    : [categories: ['Style'], points : 50000 ],
             SystemOutPrint                                    : [categories: ['Style'], points : 50000 ],

             // rulesets/naming.xml
             AbstractClassName                                 : [categories: ['Style'], points : 50000 ],
             ClassName                                         : [categories: ['Style'], points : 50000 ],
             ClassNameSameAsFilename                           : [categories: ['Style'], points : 50000 ],
             ClassNameSameAsSuperclass                         : [categories: ['Style'], points : 50000 ],
             ConfusingMethodName                               : [categories: ['Style'], points : 50000 ],
             FactoryMethodName                                 : [categories: ['Style'], points : 50000 ],
             FieldName                                         : [categories: ['Style'], points : 50000 ],
             InterfaceName                                     : [categories: ['Style'], points : 50000 ],
             InterfaceNameSameAsSuperInterface                 : [categories: ['Style'], points : 50000 ],
             MethodName                                        : [categories: ['Style'], points : 50000 ],
             ObjectOverrideMisspelledMethodName                : [categories: ['Style'], points : 50000 ],
             PackageName                                       : [categories: ['Style'], points : 50000 ],
             PackageNameMatchesFilePath                        : [categories: ['Style'], points : 50000 ],
             ParameterName                                     : [categories: ['Style'], points : 50000 ],
             PropertyName                                      : [categories: ['Style'], points : 50000 ],
             VariableName                                      : [categories: ['Style'], points : 50000 ],

             // rulesets/security.xml
             FileCreateTempFile                                : [categories: ['Security'], points : 50000 ],
             InsecureRandom                                    : [categories: ['Security'], points : 50000 ],
             JavaIoPackageAccess                               : [categories: ['Security'], points : 50000 ],
             NonFinalPublicField                               : [categories: ['Security'], points : 50000 ],
             NonFinalSubclassOfSensitiveInterface              : [categories: ['Security'], points : 50000 ],
             ObjectFinalize                                    : [categories: ['Security'], points : 50000 ],
             PublicFinalizeMethod                              : [categories: ['Security'], points : 50000 ],
             SystemExit                                        : [categories: ['Security'], points : 50000 ],
             UnsafeArrayDeclaration                            : [categories: ['Security'], points : 50000 ],

             // rulesets/serialization.xml
             EnumCustomSerializationIgnored                    : [categories: ['Bug Risk'], points : 50000 ],
             SerialPersistentFields                            : [categories: ['Bug Risk'], points : 50000 ],
             SerialVersionUID                                  : [categories: ['Bug Risk'], points : 50000 ],
             SerializableClassMustDefineSerialVersionUID       : [categories: ['Bug Risk'], points : 50000 ],

             // rulesets/size.xml
             AbcMetric                                         : [categories: ['Complexity'], points : 50000 ],  // Requires the GMetrics jar
             ClassSize                                         : [categories: ['Complexity'], points : 50000 ],
             CrapMetric                                        : [categories: ['Complexity'], points : 50000 ],  // Requires the GMetrics jar and a Cobertura coverage file
             CyclomaticComplexity                              : [categories: ['Complexity'], points : 50000 ],  // Requires the GMetrics jar
             MethodCount                                       : [categories: ['Complexity'], points : 50000 ],
             MethodSize                                        : [categories: ['Complexity'], points : 50000 ],
             NestedBlockDepth                                  : [categories: ['Complexity'], points : 50000 ],
             ParameterCount                                    : [categories: ['Complexity'], points : 50000 ],

             // rulesets/unnecessary.xml
             AddEmptyString                                    : [categories: ['Style'], points : 50000 ],
             ConsecutiveLiteralAppends                         : [categories: ['Style'], points : 50000 ],
             ConsecutiveStringConcatenation                    : [categories: ['Style'], points : 50000 ],
             UnnecessaryBigDecimalInstantiation                : [categories: ['Style'], points : 50000 ],
             UnnecessaryBigIntegerInstantiation                : [categories: ['Style'], points : 50000 ],
             UnnecessaryBooleanExpression                      : [categories: ['Style'], points : 50000 ],
             UnnecessaryBooleanInstantiation                   : [categories: ['Style'], points : 50000 ],
             UnnecessaryCallForLastElement                     : [categories: ['Style'], points : 50000 ],
             UnnecessaryCallToSubstring                        : [categories: ['Style'], points : 50000 ],
             UnnecessaryCast                                   : [categories: ['Style'], points : 50000 ],
             UnnecessaryCatchBlock                             : [categories: ['Style'], points : 50000 ],
             UnnecessaryCollectCall                            : [categories: ['Style'], points : 50000 ],
             UnnecessaryCollectionCall                         : [categories: ['Style'], points : 50000 ],
             UnnecessaryConstructor                            : [categories: ['Style'], points : 50000 ],
             UnnecessaryDefInFieldDeclaration                  : [categories: ['Style'], points : 50000 ],
             UnnecessaryDefInMethodDeclaration                 : [categories: ['Style'], points : 50000 ],
             UnnecessaryDefInVariableDeclaration               : [categories: ['Style'], points : 50000 ],
             UnnecessaryDotClass                               : [categories: ['Style'], points : 50000 ],
             UnnecessaryDoubleInstantiation                    : [categories: ['Style'], points : 50000 ],
             UnnecessaryElseStatement                          : [categories: ['Style'], points : 50000 ],
             UnnecessaryFinalOnPrivateMethod                   : [categories: ['Style'], points : 50000 ],
             UnnecessaryFloatInstantiation                     : [categories: ['Style'], points : 50000 ],
             UnnecessaryGString                                : [categories: ['Style'], points : 50000 ],
             UnnecessaryGetter                                 : [categories: ['Style'], points : 50000 ],
             UnnecessaryIfStatement                            : [categories: ['Style'], points : 50000 ],
             UnnecessaryInstanceOfCheck                        : [categories: ['Style'], points : 50000 ],
             UnnecessaryInstantiationToGetClass                : [categories: ['Style'], points : 50000 ],
             UnnecessaryIntegerInstantiation                   : [categories: ['Style'], points : 50000 ],
             UnnecessaryLongInstantiation                      : [categories: ['Style'], points : 50000 ],
             UnnecessaryModOne                                 : [categories: ['Style'], points : 50000 ],
             UnnecessaryNullCheck                              : [categories: ['Style'], points : 50000 ],
             UnnecessaryNullCheckBeforeInstanceOf              : [categories: ['Style'], points : 50000 ],
             UnnecessaryObjectReferences                       : [categories: ['Style'], points : 50000 ],
             UnnecessaryOverridingMethod                       : [categories: ['Style'], points : 50000 ],
             UnnecessaryPackageReference                       : [categories: ['Style'], points : 50000 ],
             UnnecessaryParenthesesForMethodCallWithClosure    : [categories: ['Style'], points : 50000 ],
             UnnecessaryPublicModifier                         : [categories: ['Style'], points : 50000 ],
             UnnecessaryReturnKeyword                          : [categories: ['Style'], points : 50000 ],
             UnnecessarySafeNavigationOperator                 : [categories: ['Style'], points : 50000 ],
             UnnecessarySelfAssignment                         : [categories: ['Style'], points : 50000 ],
             UnnecessarySemicolon                              : [categories: ['Style'], points : 50000 ],
             UnnecessarySetter                                 : [categories: ['Style'], points : 50000 ],
             UnnecessaryStringInstantiation                    : [categories: ['Style'], points : 50000 ],
             UnnecessarySubstring                              : [categories: ['Style'], points : 50000 ],
             UnnecessaryTernaryExpression                      : [categories: ['Style'], points : 50000 ],
             UnnecessaryToString                               : [categories: ['Style'], points : 50000 ],
             UnnecessaryTransientModifier                      : [categories: ['Style'], points : 50000 ],

             // rulesets/unused.xml
             UnusedArray                                       : [categories: ['Style'], points : 50000 ],
             UnusedMethodParameter                             : [categories: ['Style'], points : 50000 ],
             UnusedObject                                      : [categories: ['Style'], points : 50000 ],
             UnusedPrivateField                                : [categories: ['Style'], points : 50000 ],
             UnusedPrivateMethod                               : [categories: ['Style'], points : 50000 ],
             UnusedPrivateMethodParameter                      : [categories: ['Style'], points : 50000 ],
             UnusedVariable                                    : [categories: ['Style'], points : 50000 ],
            ]
}